---
language: python
python: 2.7

sudo: required
dist: xenial
env: OS=xenial

matrix:
  include:
    - os: linux
      dist: trusty
      env: OS=trusty
    - os: linux
      dist: centos
      env: OS=centos
    - os: linux
      dist: jessie
      env: OS=jessie

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Add roles path
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Get latest versions of openssl/wget
  - (apt-get update && apt-get -y install openssl wget ) || yum -y install openssl openssl-libs wget

script:
  # Basic role syntax check
  - ansible-playbook --connection=local tests/test.yml -i tests/inventory --syntax-check

  # Test role.
  - ansible-playbook --connection=local -D tests/test.yml -i tests/inventory

  # Test role idempotence.
  - idempotence=$(mktemp)
  - ansible-playbook --connection=local -D tests/test.yml -i tests/inventory | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
