---
language: python
python: 2.7

sudo: required
#dist: xenial
#env: OS=xenial

matrix:
  include:
    - os: linux
      dist: trusty
      env: OS=trusty
    - os: linux
      dist: centos
      env: OS=centos
    - os: linux
      dist: jessie
      env: OS=jessie

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Add roles path
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Get the splunkforwarder package
  - wget -O files/splunkforwarder-6.6.1-x86_64.rpm https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=6.6.1&product=universalforwarder&filename=splunkforwarder-6.6.1-aeae3fe0c5af-linux-2.6-x86_64.rpm&wget=true
  - wget -O files/splunkforwarder-6.6.1-x86_64.deb https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=6.6.1&product=universalforwarder&filename=splunkforwarder-6.6.1-aeae3fe0c5af-linux-2.6-amd64.deb&wget=true
  - ls -l files

script:
  # Basic role syntax check
  - sudo ansible-playbook --connection=local tests/test.yml -i tests/inventory --syntax-check

  # Test role.
  - sudo ansible-playbook --connection=local -D tests/test.yml -i tests/inventory

  # Test role idempotence.
  - idempotence=$(mktemp)
  - sudo ansible-playbook --connection=local -D tests/test.yml -i tests/inventory | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
