---
# handlers file for ansible-splunk-forwarder
- name: restart splunk
  command: "su - {{ splunk_nix_user }} -c '/opt/splunkforwarder/bin/splunk restart --accept-license --answer-yes'"
  args:
    warn: false
